import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Inter} from 'next/font/google'
import App from "@/app/app";
import  SessionProvider  from "@/app/database/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter ({subsets :['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session ={session}>
        <App>{children} </App>
        </SessionProvider>
      </body>
    </html>
  );
}
